# Faça um programa que leia um numero inteiro qualquer e mostre na tela a sua tabuada

#minha resposta
print('', '\033[1;34m-'*40, '\n', '|', '\033[7;33m          TABUADA DOS NUMEROS        \033[m\033[1;34m|')
print('', '-'*40, '\033[m')
n = int(input('\033[1;31mEscolha um numero: \033[m'))
print('{} X {:2} ={}'.format(n, 1, n*1))
print('{} X {:2} = {}'.format(n, 2, n*2))
print('{} X {:2} = {}'.format(n, 3, n*3))
print('{} X {:2} = {}'.format(n, 4, n*4))
print('{} X {:2} = {}'.format(n, 5, n*5))
print('{} X {:2} = {}'.format(n, 6, n*6))
print('{} X {:2} = {}'.format(n, 7, n*7))
print('{} X {:2} = {}'.format(n, 8, n*8))
print('{} X {:2} = {}'.format(n, 9, n*9))
print('{} X {:2} = {}'.format(n, 10, n*10))
print ('\033[1;34m-'*40)

#Resposta do Gustavo
num = int(input('Digite um numero para ver sua tabuada: '))
print('-' * 12)
print('{} X {:2} ={}'.format(num, 1, num*1))
print('{} X {:2} ={}'.format(num, 2, num*2))
print('{} X {:2} ={}'.format(num, 3, num*3))
print('{} X {:2} ={}'.format(num, 4, num*4))
print('{} X {:2} ={}'.format(num, 5, num*5))
print('{} X {:2} ={}'.format(num, 6, num*6))
print('{} X {:2} ={}'.format(num, 7, num*7))
print('{} X {:2} ={}'.format(num, 8, num*8))
print('{} X {:2} ={}'.format(num, 9, num*9))
print('{} X {:2} ={}'.format(num, 10, num*10))
print('-' * 12)
